### ISSUE TITLE
[Feat/StoreDetailScene/StoreDetailVC] StoreDetailVC 제작

### ISSUE THREAD

**Issue by anyukyung** [YAPP-Github/21st-ALL-Rounder-Team-1-iOS#16]
# 📌 Issue
- StoreDetailVC를 제작하는 이슈입니다.
- 맨위 이미지는 추후에 paging 될 가능성이 있어보이나 지금은 따로 서브클래싱을 하지 않고 ImageView로 제작할 예정입니다.
- 아래에는 제작해둔 StoreDetailInfoView를 넣고, TapMan 라이브러리를 이용해 구현할 예정입니다.
TapMan 라이브러리는 dev 브랜치에서 설치하도록 하겠습니다. 추후에는 라이브러리를 걷어내고 커스텀할 예정입니다.
- TapMan의 첫번째 탭안에 StoreDetailTableView를 위치시키는 것까지 이 이슈에서 할 예정입니다.
- 전체가 스크롤되어야하기 때문에 전체 뷰를 TableView안에 위치시켜 구현하려고 합니다.
(이 부분은 이전에 조지가 어려움을 겪었던 부분이기도 해서, 저도 구현하면서 좀 유동적으로 바뀔 수도 있을 것 같습니다!)

## 📸 ScreenShot
(선택) 이슈와 관련된 화면을 첨부해주세요.
<img width="192" alt="스크린샷 2022-11-27 오전 4 56 51" src="https://user-images.githubusercontent.com/70168249/204106858-1090e1b8-5c3f-4d7f-ab89-f6d7c6f55366.png">

**Comment by sero3779** [comment]
@anyukyung 현재 제가 작업하게 된 화면이니 시간되실때 issue close 부탁드려요~

**Comment by anyukyung** [comment]
@Neph3779 확인 완료!
